kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: package-notebook
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sapujagad2-package-notebook
