apiVersion: v1
kind: PersistentVolume
metadata:
  name: sapujagad2-package-jupyter
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /
  storageClassName: sapujagad2-package-jupyter
