kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: package-mnt
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: sapujagad2-package-mnt
