apiVersion: v1
kind: PersistentVolume
metadata:
  name: sapujagad2-package-mnt
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/sapujagad2/"
  storageClassName: sapujagad2-package-mnt
