apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  type: LoadBalancer
  selector: {}
  publishNotReadyAddresses: true
  ports:
  - name: http
    port: 9870
  - name: hdfs
    port: 8020
