
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapreduce-historyserver
spec:
  selector:
    matchLabels: {}
  serviceName: mapreduce-historyserver
  replicas: 1
  template:
    spec:
      hostname: mapreduce-historyserver
      subdomain: mapreduce-historyserver
      initContainers:
      - name: wait-for-history-dir
        image: sapujagad2-util
        args:
        - wait-for-job
        - mapreduce-mkdir
      containers:
      - name: historyserver
        image: sapujagad2-hadoop
        command:
        - $(HADOOP_HOME)/bin/mapred
        args:
        - historyserver
        envFrom:
        - configMapRef:
            name: hadoop-env
        readinessProbe:
          tcpSocket:
            port: 10020

        securityContext:
          runAsUser: 1013
          runAsGroup: 1010
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
  volumeClaimTemplates: []
