apiVersion: batch/v1
kind: Job
metadata:
  name: hive-mkdir
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-parent-dir
        image: sapujagad2-util
        args:
        - wait-for-job
        - hdfs-mkdir
      containers:
      - name: mkdir
        image: sapujagad2-util
        securityContext:
          runAsUser: 0 
        command:
        - /bin/bash
        - -c
        - echo "hdfs-namenode.sapujagad2.svc.cluster.local hdfs-namenode-0.hdfs-namenode" >> /etc/hosts
        args:
        - -c
        - |
          docker-entrypoint.sh hdfs-mkdir /user/hive hive:hive 751
          docker-entrypoint.sh hdfs-mkdir /user/hive/warehouse hive:hive 1777
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
