apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager
spec:
  type: LoadBalancer
  selector: {}
  publishNotReadyAddresses: true
  ports:
  - name: webapp
    port: 8088
  - name: openport
    port: 8032
  - name: openportyarn
    port: 8031
  - name: openportyarnk
    port: 8030
  - name: openportyarnt
    port: 8033
