apiVersion: batch/v1
kind: Job
metadata:
  name: package-trino
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - master-1
      containers:
      - name: sapujagad2-trino
        image: sapujagad2-trino
        command:
        - /bin/bash
        args:
        - -c
        - |
          rm -rf /mnt/sapujagad2/trino
          mkdir /mnt/sapujagad2/trino
          cp -R /opt/trino/trino-cli /mnt/sapujagad2/trino/trino-cli
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: package-home
          mountPath: /mnt/sapujagad2
      restartPolicy: Never
      volumes:
      - name: package-home
        hostPath:
          path: /dev/sda1/sapujagad2/
