apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besapu-node
spec:
  selector:
    matchLabels: {}
  serviceName: besapu-node
  replicas: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - worker-3
      containers:
      - name: sleep
        image: sapujagad2-jupyter-test
        command: ["jupyterhub"]
        args: ["--config", "/etc/jupyterhub/jupyterhub_config.py"]
        envFrom:
        - configMapRef:
            name: aws-env
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: hbase-env
        - configMapRef:
            name: hive-env
        - configMapRef:
            name: ozone-env
        - configMapRef:
            name: spark-env
        - configMapRef:
            name: tez-env
        - configMapRef:
            name: trino-env
        - configMapRef:
            name: zookeeper-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        - name: HADOOP_CLASSPATH
          value: $(TEZ_CONF_DIR):$(TEZ_JARS)/*:$(TEZ_JARS)/lib/*
        - name: JAVA_HOME
          value: /usr/local/openjdk-8/
        - name: JUPYTERHUB_ADMIN
          value: admin
#        - name: SPARK_DIST_CLASSPATH
#          value: /etc/hadoop/conf:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.563.jar:/opt/hadoop/share/hadoop/tools/lib/hadoop-aws-3.2.2.jar:/opt/hadoop/share/hadoop/hdfs:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*:/opt/hadoop/share/hadoop/mapreduce/lib/*:/opt/hadoop/share/hadoop/mapreduce/*:/opt/hadoop/share/hadoop/yarn:/opt/hadoop/share/hadoop/yarn/lib/*:/opt/hadoop/share/hadoop/yarn/*:/etc/tez/conf:/opt/tez/LICENSE:/opt/tez/LICENSE-BSD-3clause:/opt/tez/LICENSE-CDDLv1.0:/opt/tez/LICENSE-CDDLv1.1-GPLv2_withCPE:/opt/tez/LICENSE-MIT:/opt/tez/LICENSE-SIL_OpenFontLicense-v1.1:/opt/tez/NOTICE:/opt/tez/hadoop-shim-0.10.2.jar:/opt/tez/hadoop-shim-2.8-0.10.2.jar:/opt/tez/lib:/opt/tez/share:/opt/tez/tez-api-0.10.2.jar:/opt/tez/tez-build-tools-0.10.2.jar:/opt/tez/tez-common-0.10.2.jar:/opt/tez/tez-dag-0.10.2.jar:/opt/tez/tez-examples-0.10.2.jar:/opt/tez/tez-history-parser-0.10.2.jar:/opt/tez/tez-javadoc-tools-0.10.2.jar:/opt/tez/tez-job-analyzer-0.10.2.jar:/opt/tez/tez-mapreduce-0.10.2.jar:/opt/tez/tez-protobuf-history-plugin-0.10.2.jar:/opt/tez/tez-runtime-internals-0.10.2.jar:/opt/tez/tez-runtime-library-0.10.2.jar:/opt/tez/tez-tests-0.10.2.jar:/opt/tez/tez-tfile-parser-0.10.2.jar:/opt/tez/tez-yarn-timeline-cache-plugin-0.10.2.jar:/opt/tez/tez-yarn-timeline-history-0.10.2.jar:/opt/tez/tez-yarn-timeline-history-with-acls-0.10.2.jar:/opt/tez/tez-yarn-timeline-history-with-fs-0.10.2.jar:/opt/tez/lib/RoaringBitmap-0.7.45.jar:/opt/tez/lib/async-http-client-2.12.3.jar:/opt/tez/lib/commons-cli-1.2.jar:/opt/tez/lib/commons-codec-1.11.jar:/opt/tez/lib/commons-collections4-4.1.jar:/opt/tez/lib/commons-io-2.8.0.jar:/opt/tez/lib/commons-lang-2.6.jar:/opt/tez/lib/guava-31.1-jre.jar:/opt/tez/lib/hadoop-hdfs-client-3.3.1.jar:/opt/tez/lib/hadoop-yarn-server-timeline-pluginstorage-3.3.1.jar:/opt/tez/lib/javax.servlet-api-3.1.0.jar:/opt/tez/lib/jersey-client-1.19.jar:/opt/tez/lib/jersey-json-1.19.jar:/opt/tez/lib/jettison-1.3.4.jar:/opt/tez/lib/jsr305-3.0.0.jar:/opt/tez/lib/metrics-core-3.1.0.jar:/opt/tez/lib/netty-all-4.1.72.Final.jar:/opt/tez/lib/pig-0.13.0.jar:/opt/tez/lib/protobuf-java-2.5.0.jar
        - name: PATH
          value: /opt/oracle/instantclient_21_12:/opt/mssql-tools18/bin:/opt/mssql-tools/bin:$(TRINO_HOME)/trino-cli/bin:$(HBASE_HOME)/bin:$(HIVE_HOME)/bin:$(OZONE_HOME)/bin:$(SPARK_HOME)/bin:$(HADOOP_HOME)/bin:/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: hbase-conf
          mountPath: /etc/hbase/conf
        - name: hive-conf
          mountPath: /etc/hive/conf
        - name: ozone-conf
          mountPath: /etc/ozone/conf
        - name: spark-conf
          mountPath: /etc/spark/conf
        - name: tez-conf
          mountPath: /etc/tez/conf
        - name: trino-conf
          mountPath: /etc/trino/conf/cli.properties
          subPath: cli.properties
        - name: zookeeper-conf
          mountPath: /etc/zookeeper/conf
        - name: package-hadoop
          mountPath: /opt/hadoop
        - name: package-hbase-client
          mountPath: /opt/hbase
        - name: package-hive
          mountPath: /opt/hive
        - name: package-ozone
          mountPath: /opt/ozone
        - name: package-spark
          mountPath: /opt/spark
        - name: package-tez
          mountPath: /opt/tez
        - name: package-trino
          mountPath: /opt/trino
#        - name: package-zookeeper
#          mountPath: /opt/zookeeper
        - name: package-jupyter
          mountPath: /data
        - name: jupyterhub-conf
          mountPath: /etc/jupyterhub/
        workingDir: /home/zookage
      terminationGracePeriodSeconds: 0
      volumes:
      - name: jupyterhub-conf
        configMap:
          name: jupyterhub-conf
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: hbase-conf
        configMap:
          name: hbase-conf
      - name: hive-conf
        configMap:
          name: hive-conf
      - name: ozone-conf
        configMap:
          name: ozone-conf
      - name: spark-conf
        configMap:
          name: spark-conf
      - name: tez-conf
        configMap:
          name: tez-conf
      - name: trino-conf
        configMap:
          name: trino-conf
      - name: zookeeper-conf
        configMap:
          name: zookeeper-conf
      - name: package-hadoop
        persistentVolumeClaim:
          claimName: package-hadoop
      - name: package-hbase-client
        persistentVolumeClaim:
          claimName: package-hbase-client
      - name: package-hive
        persistentVolumeClaim:
          claimName: package-hive
      - name: package-ozone
        persistentVolumeClaim:
          claimName: package-ozone
      - name: package-spark
        persistentVolumeClaim:
          claimName: package-spark
      - name: package-tez
        persistentVolumeClaim:
          claimName: package-tez
      - name: package-trino
        persistentVolumeClaim:
          claimName: package-trino
#      - name: package-zookeeper
#        persistentVolumeClaim:
#          claimName: package-zookeeper
      - name: package-jupyter
        persistentVolumeClaim:
          claimName: package-jupyter
  volumeClaimTemplates: []
