apiVersion: batch/v1
kind: Job
metadata:
  name: package-zookeeper
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - master-1
      containers:
      - name: sapujagad2-zookeeper
        image: sapujagad2-zookeeper
        command:
        - /bin/bash
        args:
        - -c
        - "rm -rf /mnt/sapujagad2/zookeeper && cp -R /opt/zookeeper /mnt/sapujagad2/zookeeper"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: package-home
          mountPath: /mnt/sapujagad2
      restartPolicy: Never
      volumes:
      - name: package-home
        hostPath:
          path: /opt/sapujagad2/
